export const GET_NUTS_POP = 'GET_NUTS_POP';
export const GET_NUTS_POP2 = 'GET_NUTS_POP2';
export const GET_POP_FROM_MUNICIPALITY = 'GET_POP_FROM_MUNICIPALITY';
export const NUTS = 'NUTS';
export const LAU = 'LAU';
export const GET_LAU_AGE_POP = 'GET_LAU_AGE_POP';
export const GET_SCHOOLS_ON_TYPE = 'GET_SCHOOLS_ON_TYPE';
export const GET_SCHOOL_YEARS = 'GET_SCHOOL_YEARS';
export const GET_NUMBER_SCHOOLS = 'GET_NUMBER_SCHOOLS';
export const GET_NUMBER_SCHOOLS_BY_TYPE = 'GET_NUMBER_SCHOOLS_BY_TYPE';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_ISCED = 'GET_ISCED';
export const GET_SCHOOLS_FROM_MUNICIPALITY = 'GET_SCHOOLS_FROM_MUNICIPALITY';
export const GET_LAU_FROM_NUTS = 'GET_LAU_FROM_NUTS';
export const POP_IN_SCHOOL_AGE = 'POP_IN_SCHOOL_AGE';
export const POINT_FROM_LAUCODE = 'POINT_FROM_LAUCODE';

